# Generated by Django 4.1.13 on 2025-11-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0033_dependant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultancy_fee',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
    ]
