# Generated by Django 4.1.13 on 2025-11-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0034_alter_appointment_consultancy_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregistration',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
    ]
