# Generated by Django 4.1.13 on 2025-11-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0035_staffregistration_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.staffregistration'),
        ),
    ]
