# Generated by Django 4.1.13 on 2025-11-14 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0036_appointment_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='staffregistration',
            name='gender',
        ),
    ]
