# Generated by Django 4.1.13 on 2025-12-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0038_alter_customuser_user_type_hospitalregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalregistration',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
