# Generated by Django 4.1.13 on 2025-12-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0039_hospitalregistration_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralappointment',
            name='hospital_reffered',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
