# Generated by Django 4.1.13 on 2025-12-03 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0040_referralappointment_hospital_reffered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralappointment',
            name='hospital_reffered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.hospitalregistration'),
        ),
    ]
