# Generated by Django 4.1.13 on 2025-12-03 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0041_alter_referralappointment_hospital_reffered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralappointment',
            name='hospital_reffered',
        ),
        migrations.AlterField(
            model_name='referralappointment',
            name='hospital_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.hospitalregistration'),
        ),
    ]
