# Generated by Django 4.1.13 on 2025-12-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0042_remove_referralappointment_hospital_reffered_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.AddField(
            model_name='referralappointment',
            name='referral_status',
            field=models.CharField(choices=[('Not Visited', 'Not Visited'), ('Visited', 'Visited')], default='Not Visited', max_length=250),
        ),
    ]
