# Generated by Django 4.1.13 on 2025-12-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0043_delete_hospital_referralappointment_referral_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralappointment',
            name='diagnosis',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='referralappointment',
            name='prescription',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='referralappointment',
            name='referral_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
