# Generated by Django 4.1.13 on 2025-12-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0044_referralappointment_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralappointment',
            name='paid_by_insurance',
            field=models.BooleanField(default=False),
        ),
    ]
