# Generated by Django 4.1.13 on 2025-12-07 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0045_referralappointment_paid_by_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.hospitalregistration')),
                ('pat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.patientreg')),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.referralappointment')),
            ],
        ),
    ]
