# Generated by Django 4.1.13 on 2025-12-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0046_medicalclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpatient',
            name='pharmacy_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
