# Generated by Django 4.1.13 on 2025-12-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0049_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staff_id',
            new_name='Pf_number',
        ),
    ]
