# Generated by Django 4.1.13 on 2025-12-26 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0050_rename_staff_id_staff_pf_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreg',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.staff'),
        ),
    ]
