# Generated by Django 4.1.13 on 2025-12-27 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0052_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreg',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.students'),
        ),
    ]
