# Generated by Django 4.1.13 on 2026-01-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0055_doctoravailablity_delete_doctoravailability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorAvailablity',
        ),
    ]
