# Generated by Django 4.1.13 on 2026-01-05 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0056_delete_doctoravailablity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailablity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.doctorregistration')),
            ],
        ),
    ]
