# Generated by Django 4.1.13 on 2026-01-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0057_doctoravailablity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorAvailablity',
            new_name='DoctorAvailability',
        ),
    ]
