# Generated by Django 4.1.13 on 2026-01-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0058_rename_doctoravailablity_doctoravailability'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorAvailability',
            new_name='DoctAvailability',
        ),
    ]
