# Generated by Django 4.1.13 on 2026-01-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0059_rename_doctoravailability_doctavailability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctAvailability',
        ),
    ]
