# Generated by Django 4.1.13 on 2026-01-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0061_doctavailability'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctAvailability',
            new_name='DoctorAvailability',
        ),
    ]
