# Generated by Django 4.1.13 on 2026-01-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0062_rename_doctavailability_doctoravailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_of_appointment',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_of_appointment',
            field=models.TimeField(),
        ),
    ]
