# Generated by Django 4.1.13 on 2026-01-06 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0063_alter_appointment_date_of_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralappointment',
            name='dependant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.dependant'),
        ),
    ]
