# Generated by Django 4.1.13 on 2026-01-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0065_alter_referralappointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booking_fee',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
