# Generated by Django 4.1.13 on 2026-01-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0066_appointment_booking_fee_payment_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicalcllaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=250)),
                ('visitdate', models.DateField()),
                ('patienttype', models.CharField(max_length=250)),
                ('receipt_image', models.ImageField(upload_to='')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
