# Generated by Django 4.1.13 on 2026-01-08 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0067_medicalcllaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcllaim',
            name='decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalcllaim',
            name='doctor_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalcllaim',
            name='doctor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.doctorregistration'),
        ),
        migrations.AddField(
            model_name='medicalcllaim',
            name='dvc_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalcllaim',
            name='finance_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalcllaim',
            name='hr_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalcllaim',
            name='pat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.patientreg'),
        ),
        migrations.AlterField(
            model_name='medicalcllaim',
            name='patienttype',
            field=models.CharField(choices=[('outpatient', 'Outpatient'), ('inpatient', 'Inpatient')], max_length=20),
        ),
    ]
