# Generated by Django 4.1.13 on 2026-01-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0068_medicalcllaim_decline_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcllaim',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('doctor_approved', 'Approved by Doctor'), ('hr_approved', 'Approved by HR'), ('dvc_approved', 'Approved by DVC'), ('finance_approved', 'Approved by Finance'), ('declined', 'Declined')], default='submitted', max_length=20),
        ),
    ]
