# Generated by Django 4.1.13 on 2026-01-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0069_medicalcllaim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcllaim',
            name='visitdate',
            field=models.DateField(max_length=20),
        ),
    ]
