# Generated by Django 4.1.13 on 2026-01-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0071_alter_medicalcllaim_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcllaim',
            name='doctor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.doctorregistration'),
        ),
    ]
