# Generated by Django 4.1.13 on 2026-01-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0072_alter_medicalcllaim_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcllaim',
            name='patienttype',
            field=models.CharField(choices=[('Outpatient', 'Outpatient'), ('Inpatient', 'Inpatient')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalcllaim',
            name='status',
            field=models.CharField(choices=[('Submitted', 'submitted'), ('doctor_approved', 'Approved by Doctor'), ('hr_approved', 'Approved by HR'), ('dvc_approved', 'Approved by DVC'), ('finance_approved', 'Approved by Finance'), ('declined', 'Declined')], default='submittted', max_length=20),
        ),
    ]
