# Generated by Django 4.1.13 on 2026-01-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0073_alter_medicalcllaim_patienttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcllaim',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('doctor_approved', 'Approved by Doctor'), ('hr_approved', 'Approved by HR'), ('dvc_approved', 'Approved by DVC'), ('finance_approved', 'Approved by Finance'), ('declined', 'Declined')], default='submittted', max_length=20),
        ),
    ]
