# Generated by Django 4.1.13 on 2026-01-13 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0074_alter_medicalcllaim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'doctor'), (3, 'patient'), (4, 'staff'), (5, 'pharmacist'), (6, 'hospital'), (6, 'HR')], default=1),
        ),
        migrations.AlterField(
            model_name='medicalcllaim',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('doctor_approved', 'Approved by Doctor'), ('hr_approved', 'Approved by HR'), ('dvc_approved', 'Approved by DVC'), ('finance_approved', 'Approved by Finance'), ('declined', 'Declined')], default='submitted', max_length=20),
        ),
        migrations.CreateModel(
            name='HRregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regdate_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regdate_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DVCregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regdate_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
