# Generated by Django 4.1.13 on 2026-01-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0075_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'doctor'), (3, 'patient'), (4, 'staff'), (5, 'pharmacist'), (6, 'hospital'), (7, 'HR')], default=1),
        ),
    ]
