# Generated by Django 4.1.13 on 2026-01-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0076_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'doctor'), (3, 'patient'), (4, 'staff'), (5, 'pharmacist'), (6, 'hospital'), (7, 'HR'), (8, 'DVC'), (9, 'finance')], default=1),
        ),
    ]
