# Generated by Django 4.1.13 on 2026-01-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0077_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralappointment',
            name='student_status',
            field=models.CharField(choices=[('sent', 'sent'), ('Received', 'Received')], default='sent', max_length=20),
        ),
    ]
