# Generated by Django 4.1.13 on 2026-01-14 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0078_referralappointment_student_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralappointment',
            name='student_status',
        ),
        migrations.CreateModel(
            name='StudentReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_referral', models.CharField(max_length=250)),
                ('time_of_referral', models.CharField(max_length=250)),
                ('student_status', models.CharField(choices=[('sent', 'sent'), ('Received', 'Received')], default='sent', max_length=20)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.doctorregistration')),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.hospitalregistration')),
                ('pat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.patientreg')),
            ],
        ),
    ]
