# Generated by Django 4.1.13 on 2026-01-15 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0079_remove_referralappointment_student_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralappointment',
            name='doctor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.doctorregistration'),
        ),
    ]
