# Generated by Django 4.1.13 on 2026-01-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0080_alter_referralappointment_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregistration',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
