# Generated by Django 4.1.13 on 2026-01-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0081_staffregistration_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralappointment',
            name='patient_type',
            field=models.CharField(choices=[('Outpatient', 'Outpatient'), ('Inpatient', 'Inpatient')], default='Outpatient', max_length=20),
        ),
    ]
